# Generated by Django 5.0.3 on 2024-03-11 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0002_alter_contract_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agent_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.agent'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='comment_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_app.comment'),
        ),
    ]
