# Generated by Django 5.0.3 on 2024-03-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_contract_agent_id_alter_contract_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='file_path',
            field=models.FileField(null=True, upload_to='files/'),
        ),
    ]
